import React from 'react';
import { ProcessedImage } from '../types';

interface ResultViewProps {
  image: ProcessedImage;
  onReset: () => void;
}

const ResultView: React.FC<ResultViewProps> = ({ image, onReset }) => {
  const handleDownload = () => {
    if (!image.processedUrl) return;
    const link = document.createElement('a');
    link.href = image.processedUrl;
    link.download = 'removed-bg-gemini.png';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="w-full max-w-6xl mx-auto mt-8 px-4 animate-fade-in-up">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold text-gray-800">Image Processed</h2>
        <button 
          onClick={onReset}
          className="text-gray-500 hover:text-gray-900 text-sm font-medium flex items-center gap-1"
        >
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor" className="w-4 h-4">
            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
          Upload New
        </button>
      </div>

      <div className="bg-white rounded-2xl shadow-lg p-6 md:p-8">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          
          {/* Original */}
          <div className="flex flex-col gap-3">
            <div className="flex justify-between items-center">
              <span className="text-sm font-semibold text-gray-500 uppercase tracking-wider">Original</span>
            </div>
            <div className="relative rounded-xl overflow-hidden bg-gray-100 border border-gray-200 aspect-square md:aspect-auto h-[400px]">
              <img 
                src={image.originalUrl} 
                alt="Original" 
                className="w-full h-full object-contain"
              />
            </div>
          </div>

          {/* Processed */}
          <div className="flex flex-col gap-3">
            <div className="flex justify-between items-center">
              <span className="text-sm font-semibold text-brand-600 uppercase tracking-wider">Transparent Background</span>
            </div>
            
            <div className="relative rounded-xl overflow-hidden border border-gray-200 aspect-square md:aspect-auto h-[400px] bg-checkerboard group">
              {image.processedUrl ? (
                <img 
                  src={image.processedUrl} 
                  alt="Processed" 
                  className="w-full h-full object-contain z-10 relative"
                />
              ) : (
                <div className="w-full h-full flex items-center justify-center text-gray-400">
                    Failed to load image.
                </div>
              )}
            </div>
            
            <div className="mt-4 flex flex-col sm:flex-row gap-4">
              <button 
                onClick={handleDownload}
                className="flex-1 bg-brand-600 hover:bg-brand-700 text-white font-bold py-3 px-6 rounded-full shadow-lg transition-transform hover:-translate-y-0.5 flex items-center justify-center gap-2"
              >
                Download Transparent PNG
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor" className="w-5 h-5">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M12 12.75l4.5-4.5m-4.5 4.5l-4.5-4.5M12 12.75V3" />
                </svg>
              </button>
               <button 
                className="flex-1 bg-gray-100 hover:bg-gray-200 text-gray-800 font-bold py-3 px-6 rounded-full transition-colors flex items-center justify-center gap-2 cursor-not-allowed opacity-70"
                title="Feature coming soon"
              >
                Edit High-Res
                 <span className="bg-gray-300 text-[10px] px-1.5 py-0.5 rounded text-gray-600 font-extrabold uppercase">Soon</span>
              </button>
            </div>
             <p className="text-xs text-gray-400 text-center mt-2">
                Generated by Gemini 2.5 Flash Image.
            </p>
          </div>

        </div>
      </div>
    </div>
  );
};

export default ResultView;